### ISSUE TITLE
:from != :from_file

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#137]
In `lib/how_is/cli.rb`, there's a place where `:from_file` is used instead of `:from`, which breaks the `--from` flag. This should be fixed, and a test that would catch this failure should be added.

**Comment by duckinator** [comment]
😳 apparently --from is broken as _hell_, and there's no tests for it.

**Comment by duckinator** [comment]
working on this has made it abundantly clear that all of the internal APIs are just as bad as the external API was before the API overhaul.

**Comment by olleolleolle** [comment]
You, on the other hand, rock!
