### ISSUE TITLE
No report and Hashie::Mash#default warnings

### ISSUE THREAD

**Issue by cllns** [how-is/how_is#154]
HowIs seems like a great project :)

Unfortunately, on both ruby `2.3.3` and `2.4.1`, when I do:
```shell
gem install how_is
how_is rubygems/rubygems
```
(adding `--report report.html` does the same, and it does this for other repos too)

I only get:
```
W, [2017-04-20T10:33:40.990522 #86839]  WARN -- : You are setting a key that conflicts with a built-in method Hashie::Mash#default defined in Hash. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method.
```
about 30 times or so.

And the report just prints out the object:
```
% cat report.html
#<HowIs:0x007fadc08c0ee0>%
```

Any idea why this is happening or how I can fix it?

**Comment by duckinator** [comment]
Thanks for opening the issue! These are two distinct problems, and both are known: #150 for the printing out an object, #124 for the warnings. PR #150 fixes the printing out an object, but I forgot to make a new release after that was merged.

The warnings shouldn't cause any problems, other than being annoying. I'll make a new release ASAP, which should make it actually generate reports again.

I'll leave another comment here + close this issue when the new version is released.

**Comment by duckinator** [comment]
Hey, sorry about the delay with this.

[v18.0.3](https://github.com/how-is/how_is/blob/master/CHANGELOG.md#v1803) has been released!

It fixes the problem with it printing out an object, but the warnings will still be there.

I'm going to go ahead and close this issue, since there's another issue open about the warnings.

**Comment by duckinator** [comment]
@cllns fyi, v18.0.4 was released and fixes the warnings.

**Comment by cllns** [comment]
@duckinator thanks :)
