### ISSUE TITLE
Refactor + improve tests for Contributions class

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#194]
Refactoring:

1. [x] Combine `#pretty_start_date` and `#pretty_end_date` into `#pretty_date(date)`
2. [x] Make the `#pretty_date` method private.
3. [x] Move `#default_branch` to between `#compare_url` and `#summary`, so relevant methods are grouped together.
4. [x] Make `#changes` more robust. (do after writing tests)

---

Methods that need tests on the `Contributions` class:

* [x] `#commits` (implicitly tests `#commit`, since it includes `#commit`'s output)
* [x] `#changes`
* [x] `#changed_files`
* [x] `#additions_count`
* [x] `#deletions_count`
* [x] `#compare_url`
* [x] `#pretty_date`
* [x] `#summary`

---

Re making `#changes` more robust:

Change

https://github.com/how-is/how_is/blob/cf10219d64bf85f550255a01bf9e2c2a4986e7e8/lib/how_is/contributions.rb#L90-L92 

to something like

```ruby
@stats.keys.each do |key|
  @stats[key] += commit.stats[key]
end
```

so it doesn't break if GitHub returns more stats in the future.

**Comment by olleolleolle** [comment]
Can some of the checkboxes now be ticked?

**Comment by duckinator** [comment]
just went through and updated it. looks like most of the refactoring is done, but it still needs tests. thanks for pointing that out!
