### ISSUE TITLE
Contributions: look up default_branch in GitHub API

### ISSUE THREAD

**Issue by olleolleolle** [how-is/how_is#195]
The `repos/` endpoint has `default_branch` information. Look it up and use it.

At the moment, HowIs hard-codes it to `"master"`.

https://developer.github.com/v3/repos/#get

```
    "default_branch": "master",
```

**Comment by duckinator** [comment]
I poked at this real quick. Not sure how to get the github_api gem that HowIs uses to return information from that endpoint. May have to just bullshit it and make an HTTP request using Tessellator::Fetcher.
