### ISSUE TITLE
Document PR process

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#198]
Technical details:

* branch protection is enabled,
* require branches to be up-to-date before merging,
* require travis + bundlerbot + hound status checks to pass before merging (so I don't accidentally click the Merge button out of habit)
* enable "Restrict who can push to this branch", and add bundlerbot to the list

So the process is:

1. Someone makes a PR
2. When a maintainer is happy with it and Travis + Hound pass, said maintainer does `@bundlerbot r+`
3. Bundlerbot automatically merges the PR + master on a separate branch, makes sure tests still pass on Travis, and pushes it to master if they do.

**Comment by duckinator** [comment]
I have no idea what or how to document this, but it seems like it should be documented somewhere. 🤷‍

**Comment by olleolleolle** [comment]
My guess is in the CONTRIBUTING document - if there is such a thing.

**Comment by duckinator** [comment]
I mean, there _can_ be. That does seem like a good place for it.

**Comment by duckinator** [comment]
Fixed by #246.
