### ISSUE TITLE
Unknown option --report-file referenced in the README

### ISSUE THREAD

**Issue by ammancilla** [how-is/how_is#51]
The documentation [suggests](https://github.com/how-is/how_is#usage) that the option to specify the report file is `--report-file`, but that option seems to not exists. Had a quick look in the code, and the right option seems to be [--report](https://github.com/how-is/how_is/blob/master/lib/how_is/cli/parser.rb#L46).

Running: 
```ruby
how_is rubygems/rubygems --report-file report
```

Throws:
```ruby
unknown option `--report-file' (Slop::UnknownOption)
```

**Comment by duckinator** [comment]
Sorry about that, it's actually just `--report`. I'll update the documentation accordingly. Thanks for letting me know!

**Comment by duckinator** [comment]
Updated in README.
