### ISSUE TITLE
Rake task for clearing VCR cache

### ISSUE THREAD

**Issue by duckinator** [how-is/how_is#95]
Possibly add a Rake task for clearing VCR's cache (./fixtures)?

So you can do something like `rake clear_vcr_cache generate_reports:all`.

**Comment by olleolleolle** [comment]
I'll investigate this!

**Comment by olleolleolle** [comment]
@duckinator Look at this option that is in VCR: the Record Mode `:all`.

https://relishapp.com/vcr/vcr/v/3-0-3/docs/record-modes/all

> The :all record mode will:
> 
> - Record new interactions.
> - Never replay previously recorded interactions.
> This can be temporarily used to force VCR to re-record
> a cassette (i.e. to ensure the responses are not out of date)
> or can be used when you simply want to log all HTTP requests.

I like the sound of "temporarily be used".

**Comment by duckinator** [comment]
yeah, that looks like a good way to handle it!

**Comment by olleolleolle** [comment]
Temporarily adding this kind of configuration in a centralized spec_helper'y place:

```ruby
VCR.configure do |c|
  c.default_cassette_options = { :record => :all }
end
```

**Comment by olleolleolle** [comment]
So, I propose this Issue be closed without changing any code.

**Comment by duckinator** [comment]
I think I'd rather have it so you can do e.g. `rake -rspec/vcr_record_new_fixtures spec` or similar and it'll clear them.

Either way, removing this from the v19.0 milestone.
